### ISSUE TITLE
Automatically Open SoaR Simulator Window on Loading of World

### ISSUE THREAD

**Issue by jodalyst** [arantonitis/soar#2]
On Mac (10.12.6 Sierra), when I load a new world, the Simulator window does not automatically come up...I'm not sure if this is desired or not, but in general the student workflow will be Load Brain > Load World > Play...but now I need to press the Simulator button as well which gets annoying and is different from older SOAR...The vast majority of times that i would use Simulator I would have done Load World so it would be good for Load World to just bring up the simulator view automatically. Have not looked at the source yet to see if it should open and this is a Mac bug or if this is just a feature in general.

**Comment by adqm** [comment]
I think it might actually be good to merge those into a single button rather than having both (maybe clicking simulator asks for a world before actually loading the simulation, and we get rid of the 'Load World' button altogether...).

**Comment by aarant** [comment]
Part of the reason it is currently the way it is, is because you can toggle between the two modes--like if you wanted to go from Simulator to Pioneer rapidly. The act of merely loading a world module is distinct from actually opening the simulator, but I guess the only reason you'd load a world at all would be to open the simulator anyway...I'll work on this over the weekend, probably making it so that loading a world will automatically simulate a 'Simulator' button press afterwards.

Note that if you already have a brain and world loaded in a simulation, and want to reload everything, the reload button will close it, reload the modules and open a new simulation.
